#pragma once

#include <cstdint>

namespace Interrupt {

// =============================================================================
// PIT
// =============================================================================

// Function called when a PIT interrupt occurs.
// context allows the callback to access an external object.
using PitCallback = void (*)(void *context);

// Number of interrupts generated by each PIT channel.
extern volatile uint32_t pitInterruptCount[4];

// Register a callback for a PIT channel.
void setPitCallback(uint8_t channel, PitCallback callback, void *context);

// Execute the callback registered for a PIT channel.
void handlePitCallback(uint8_t channel);

// Latest sinusoidal DAC sample.
extern volatile uint16_t sinOutput;

// =============================================================================
// FTM2
// =============================================================================

// Number of FTM2 counter overflows.
extern volatile uint32_t ftm2OverflowCount;

// Timestamp of the latest FTM2 capture.
extern volatile uint32_t ftm2CaptureTime;

// Logic level of the captured signal.
// false = LOW
// true  = HIGH
extern volatile bool ftm2CaptureLevel;

// Set to true by the ISR when a new capture is available.
extern volatile bool ftm2CapturePending;

} // namespace Interrupt